import type { DowntimeActivity } from './model';
import { h, p, t } from './block-utils';

export const JUTSU_TAIJUTSU_ACTIVITY: DowntimeActivity = {
  id: 'jutsu-taijutsu',
  tileLabel: 'Taijutsu / Bukijutsu creation',
  modalTitle: 'Taijutsu / Bukijutsu creation rules',
  blocks: [
    h('Taijutsu/Bukijutsu creation rules'),
    h('STEP TWO: TAIJUTSU/BUKIJUTSU PREREQUISITE(S) & RESTRICTIONS'),
    p('The second step of developing your Taijutsu or Bukijutsu is to figure out the base requirements, how this new jutsu is activated regarding its components, and whether it will be a ranged or melee jutsu. The first step to figuring out which type of jutsu you are creating is deciding on the classification of your jutsu. Is it a Taijutsu, or a Bukijutsu?'),
    h('Taijutsu'),
    p('Martial technique that utilizes the casters body. These techniques enable a user to fight beyond the normal limits of man and push into new heights of martial prowess.'),
    h('Bukijutsu'),
    p('Martial technique that requires weapons of some sort. While not more powerful than Taijutsu, these techniques are inherently more versatile due to the variety of weapons a shinobi can utilize when using them.'),
    h('Hijutsu'),
    p('By selecting this requirement keyword your Taijutsu gains the Hijutsu Keyword, and counts as being a Clan Jutsu for you. You cannot select this Keyword if you are non-Clan.'),
    h('Medical'),
    p('By selecting this requirement keyword your jutsu will gain the Medical Keyword.'),
    h('Nature Release'),
    p('By selecting this requirement keyword your jutsu will gain one or many Nature Release Keywords.'),
    h('Required Feature'),
    p('By selecting this requirement keyword, you are required to be able to benefit from a Clan or Class feature that has a number of limited uses and recharges on a short or long rest to use this Genjutsu. You cannot add this to E-Ranks The chosen feature, must be one that has to be activated by the user. The feature must require activation of some sort from the player. Regardless of the feature chosen, when this jutsu is cast, a use of the feature is also spent as part of the cost of casting this jutsu. You do not gain the benefits of casting such a resource.'),
    h('Chakra Molding (CM)'),
    p('By selecting this Component Keyword, your taijutsu requires you to mold chakra in order to utilize it. In order to utilize a Nature Release of any type, you must add this Component Keyword.'),
    h('Mobility (M)'),
    p('By Selecting this Component Keyword, your taijutsu requires you to have at least 5 feet of movement available to you. While your jutsu doesn’t spend this movement, it requires you to be able to move your body freely. All Taijutsu and Bukijutsu must have this keyword.'),
    h('Weapon (W)'),
    p('By Selecting this Component Keyword, your Bukijutsu requires you to have a weapon available to you and within reach. Select one weapon type that this Bukijutsu requires in order to function. All Bukijutsu must have this prerequisite'),
    h('Ninja Tools (NT)'),
    p('By Selecting this Component Keyword, your taijutsu requires you to have a Ninja tool available to you and within reach. Select one Ninja Tool that this jutsu requires in order to function.\n\n\n\nNotes Chakra Molding (CM) (Mandatory for Nature Release) Mobility (M) (Mandatory for Taijutsu and Bukijutsu) Weapon (W) (Mandatory for Bukijutsu) Ninja Tools (NT) -'),
    t('Prerequisites', ['Prerequisite Keywords', 'Bonus Effect Slots'], [
      ['Hijutsu', '+0'],
      ['Medical', '+0'],
      ['Fuinjutsu', '+0'],
      ['Nature Release', '+0'],
      ['Required Feature (Short Rest)', '+1'],
      ['Required Feature (Long Rest)', '+2']
    ]),
    p('Medical +0 Nature Release +0 Required Feature (Short Rest) +1 Required Feature (Long Rest) +2'),
    h('Self'),
    p('Your jutsu has a range of self. This jutsu either will only affect you, or use you as the center of its effect radius. Select this range if your jutsu will do either of these things.'),
    h('Touch'),
    p('Your has a Range of Touch (5 Feet). Your taijutsu will only be able to apply its effects if you are able to physically touch your target creature. You must make a Melee Taijutsu attack roll to score a hit with this Range.'),
    h('Ranged'),
    p('Your jutsu has a range greater than 5 feet base. Your taijutsu will be able to travel over a distance to interact with your target creature or area. You must make a Ranged Taijutsu attack roll to score a hit with this Range.'),
    h('Weapon Range'),
    p('Your jutsu uses its weapons range as to calculate the jutsu’s range. If the weapon used is a melee weapon, you must make a Melee Taijutsu attack. If the weapon used is a ranged weapon, you must make a Ranged Taijutsu attack, unless you have the Area effect added to this jutsu.'),
    h('STEP THREE: EFFECTS'),
    p('The third Step of jutsu creation comes down to selecting your jutsu’s effects, using the list provided below. All jutsu are built using a combination of different effects with each effect having an associated Saving throw, damage type or special ability attached to it.\n\n\n\nAll Taijutsu/Bukijutsu follow a certain theme or archetype that they follow. Most jutsu fall into 4 different forms of casting. Either Offensive, Defensive, Control or Support. To describe these categories for the purposes of jutsu creation.\n\n\n\n• Offensive. Effects that deal damage, or attempts to inflict conditions or negative effects onto other creatures.\n\n\n\n• Defensive. Effects that mitigate damage in a number of ways; such as Damage reduction, resistance, immunity, temporary hit points.\n\n\n\n• Control. Effects that manipulate or impact other creatures ability to act or impose penalties of any type onto the target, such as attack/damage penalties, saving throw penalties, speed penalties, etc.\n\n\n\n• Support. Effects that aid yourself or other allied creatures by providing positive benefits, such as healing, bonuses to hit or damage, etc.\n\n\n\nDecide on no more than 2 of the above Taijutsu/Bukijutsu types. When you do, you can only choose effects from their given categories. While creating your Jutsu, keep in mind each effect you add will cost 1 Effect Slot based on the rank of the jutsu you are creating. Below you will find effect that doesn’t fit any one taijutsu/bukijutsu type, but instead enables them all.'),
    h('Area'),
    p('Your Jutsu gains an area of effect in the shape of one of the following: 10ft radius, 20ft Cone, 15ft Cube, 20ft Cylinder or 30ft Line. Creatures must succeed one of the following; (Strength, Dexterity or Constitution) save vs your Taijutsu Save DC. If your Jutsu requires any other Saving throw to avoid an additional Condition, this save becomes the jutsu’s base save omitting all other saving throws that other effects may ask for. This does not count for Effects Selected with "Secondary Effect". Reduce the Damage Die by 1, to a minimum of 1. Creatures suffer half damage and no Conditional effects on a successful save. If this effect is added to a Taijutsu/Bukijutsu of C-Rank or higher, increase the shape by 5 feet for each rank above D-Rank, the jutsu this effect is added to is. If this effect is added to a Bukijutsu with a Weapon Range, range applied to it, you instead use the weapons range.'),
    h('Clash'),
    p('Your Jutsu gains the Clash keyword.'),
    h('Lasting'),
    p('Your Jutsu increases its duration from Instant Concentration, up to 1 minute. If you apply this effect an additional time, the duration is increased to Concentration, up to 10 minutes. If you apply this effect, to a jutsu whose current casting time is a Reaction, its duration instead becomes 1 Round. If this effect is added to a jutsu with a Conditional Effect, affected creatures can attempt to remake their saving throws at the end of each of their turns to end this Jutsu\'s effects on them.'),
    h('Speedy'),
    p('Your Jutsu can be cast at a significantly faster speed than most others. The cast time of this Jutsu becomes a Bonus action. If your jutsu deals damage or heals creatures, reduce the damage or healing die by 1. You can take this effect a second time, changing the casting time to a Reaction, if you do reduce your Damage die by 2.'),
    h('Upcast'),
    p('Your Jutsu can be upcast from its current rank, increasing one of its current effects potency per rank upcast. Pick one of the following. If Damage, Shielding or Healing, increase the damage, healing or shielding the jutsu does by 2 damage/healing/shielding die, per rank upcast. (Pick one) If a Conditional Effect, increase the number of ranks of one of the chosen conditions this jutsu applies by +1, per rank upcast.\n\n\n\nNotes Self - Touch (5 feet) - Ranged Up to 30 feet Weapon Range Cannot be used for Taijutsu.'),
    h('Offensive'),
    h('Bleeding'),
    p('Conditional Effect Your Jutsu has the chance to inflict the Bleeding condition. You can only select this keyword if your Jutsu has the Slashing, Piercing or Wind damage type. Creatures Affected by your Jutsu must make a Dexterity (or Constitution, pick one at jutsu creation) save vs your Taijutsu Save DC or gain 1 rank of the Bleeding condition Reduce your damage die (if any) by 1, and an additional +1 for each rank above D-Rank this jutsu is upon creation. If this effect is added to a Taijutsu/Bukijutsu of C-Rank, failing creatures instead gain 2 ranks of Bleeding. This is increased to 3 ranks at B-Rank, 4 ranks at A-Rank and 5 ranks at S-Rank.'),
    h('Burned'),
    p('Conditional Effect Required Keywords: Nature Release (Fire Release) Your Jutsu has the chance to inflict the Burned Condition. You can only select this keyword if the Jutsu has Fire Release. Creatures affected by your jutsu must make a constitution save vs your Taijutsu save DC or suffer the Burned Condition. Reduce your damage die (if any) by 1, and an additional +1 for each rank above D-Rank this jutsu is upon creation. If this effect is added to a Taijutsu/Bukijutsu of B-Rank, failing creatures instead gain 2 ranks of Burned. This is increased to 3 ranks at S-Rank.'),
    h('Bruising'),
    p('Conditional Effect Your Jutsu has the chance to inflict the Bruised condition. Creatures affected by your jutsu must make a (Strength or Constitution) save vs your Taijutsu save DC or suffer the Bruised Condition. Reduce your damage die (if any) by 1, and an additional +1 for each rank above D-Rank this jutsu is upon creation. If this effect is added to a Taijutsu/Bukijutsu of B-Rank, failing creatures instead gain 2 ranks of Bruised. This is increased to 3 ranks at S-Rank.'),
    h('Chilled'),
    p('Conditional Effect Required Keywords: Nature Release (Water Release) Your Jutsu has the chance to inflict the Chilled condition. You can only select this Keyword if the Jutsu has Water Release. Creatures affected by your jutsu must make a constitution save vs your Taijutsu save DC or suffer the Chilled Condition. Reduce your damage die (if any) by 1. Reduce your damage die (if any) by 1, and an additional +1 for each rank above D-Rank this jutsu is upon creation. If this effect is added to a Taijutsu/Bukijutsu of B-Rank, failing creatures instead gain 2 ranks of Chilled. This is increased to 3 ranks at S-Rank.'),
    h('Corroded'),
    p('Conditional Effect Required Keywords: Bukijutsu, Medical Your Jutsu has the chance to inflict the Corroded condition. You can only select this Keyword if the Jutsu deals acid damage. Creatures affected by your jutsu must make a constitution save vs your Taijutsu save DC or suffer the Corroded Condition. Reduce your damage die (if any) by 1, and an additional +1 for each rank above D-Rank this jutsu is upon creation. If this effect is added to a Taijutsu/Bukijutsu of B-Rank, failing creatures instead gain 2 ranks of Corroded. This is increased to 3 ranks at S-Rank.'),
    h('Critical'),
    p('Increase this jutsu’s critical threat range by +1. You can add this effect an additional time, increasing this jutsu’s critical threat range by an additional +1 for each time you add this effect, after the first.'),
    h('Damage'),
    p('This Taijutsu/Bukijutsu deals damage. If this jutsu has a Nature Release, it automatically deals the chosen nature releases damage type. If your jutsu has the Medical keyword, it can automatically deal one of the listed Medical damage types (Acid, Necrotic, Poison). If your jutsu has neither Nature Release or Medical, you instead must select another damage type that you qualify for. Select one of the following damage die that your jutsu has based on its rank. Jutsu that deals more types of damage at once splits its damage evenly between each available damage die.'),
    t('Taijutsu/Bukijutsu damage die pools by rank', ['Rank', 'Damage die pools'], [
      ['D-Rank', '6d4, 4d6, 3d8, 2d10'],
      ['C-Rank', '8d4, 5d6, 4d8, 3d10, 2d12'],
      ['B-Rank', '7d6, 5d8, 5d10, 4d12'],
      ['A-Rank', '10d6, 8d8, 8d10, 6d12'],
      ['S-Rank', '12d8, 10d10, 8d12']
    ]),
    h('Damage Types'),
    p('Requirements Fire Fire Release Cold Water Release Lightning Lightning Release Wind Wind Release Earth Earth Release Bludgeoning - Slashing - Piercing - Poison Medical Acid Medical Necrotic Medical Force - Chakra Chakra Damage (Effect)'),
    h('Chakra Damage'),
    p('Required Prerequisites/Effects: Taijutsu, Touch, Chakra Molding, Damage Your Taijutsu, instead of dealing damage to a creature Hit points, deal damage to a creatures Chakra Points. Reduce your Damage die by 2. Reduce your damage die (if any) by 2 for each rank above D-Rank this jutsu is upon creation, to a minimum of 1.'),
    h('Empowered Damage'),
    p('Required Effects: Damage Your Jutsu increases its overall damage potential. Increase your damage die by 1. This effect can be taken 3 additional times after the first.'),
    h('Envenoming'),
    p('Conditional Effect Your Jutsu has the chance to inflict the Envenomed Condition. You can only select this keyword if the Jutsu has Medical. Creatures affected by your jutsu must make a constitution save vs your Taijutsu save DC or suffer the Envenomed Condition. Reduce your damage die (if any) by 1, and an additional +1 for each rank above D-Rank this jutsu is upon creation. If this effect is added to a Taijutsu/Bukijutsu of B-Rank, failing creatures instead gain 2 ranks of Envenomed. This is increased to 3 ranks at S-Rank.'),
    h('Multiple Strikes'),
    p('Required Effects: Damage Your jutsu grants you more than a single Attack Roll. Increase the number of attacks your jutsu makes by up to +1. Split your damage dice between the attacks evenly. You can take this effect one additional time. If you do, it does not cost an additional slot.'),
    h('Weakening'),
    p('Conditional Effect Your Jutsu has a chance to inflict the Weakened condition. Creatures affected by your jutsu must make a constitution save vs your Jutsu save DC or suffer the weakened condition. Reduce your damage die (if any) by 1 for each rank above D-Rank this jutsu is upon creation.'),
    h('Shocking'),
    p('Conditional Effect Your Jutsu has the chance to inflict the Shocked condition. You can only select this keyword if the jutsu has the Lightning Affinity. Reduce your damage die (if any) by 1 for each rank above D-Rank this jutsu is upon creation. If this effect is added to a Taijutsu/Bukijutsu of B-Rank, failing creatures instead gain 2 ranks of Shocked. This is increased to 3 ranks at S-Rank.'),
    h('Unarmed/Armed'),
    p('Required Keywords: Damage or Shielding Special: Does not cost a Slot. Penalty: Reduce your Damage/Shielding die by 1, to a minimum of 1. You cannot select a dice pool with only one damage/shielding die. Your Taijutsu/Bukijutsu is magnified even further. If Taijutsu, you add your unarmed damage to this Jutsu\'s damage roll. The remaining dice from the Damage effect becomes additional damage and gains whatever damage types you may have selected previously, but your Unarmed damage will always be whatever its base damage type is unless you choose to make all damage the same for this jutsu. You make this decision when creating the jutsu. If Bukijutsu, you add your weapon damage to this jutsu’s damage roll. The remaining dice from the Damage effect becomes additional damage and gains whatever damage types you may have selected previously, but your Weapon damage will always be whatever its base damage type is unless you choose to make all damage the same for this jutsu. You make this decision when creating the jutsu.'),
    h('Unavoidable'),
    p('Your Jutsu does not require creatures to make a saving throw, instead always inflicting one rank of a Condition it has on a successful hit, per casting. Select one Effect from the following, that this jutsu already has; Bleeding, Bruised, Dazed and Weakened. Affected creature gain the chosen condition. Reduce your damage die (if any) by 1, and an additional +1 for each rank above D-Rank this jutsu is upon creation.'),
    h('Defensive'),
    h('Empowered Shielding'),
    p('Required Effects: Shielding Your Jutsu increases its overall defensive potential. Increase your shielding die by 1. This effect can be taken up to 3 additional times after the first.'),
    h('Shielding'),
    p('Required Effects: Self, Lasting Your Jutsu grants temporary hit points to yourself. Select one of the following dice pools that your jutsu has based on its rank. This pool determined how much temporary hit points this jutsu grants.'),
    h('Control'),
    h('Blinding'),
    p('Conditional Effect Your jutsu has the chance to inflict the Blinded condition. Creatures affected by your jutsu must make a constitution (or wisdom, pick one at jutsu creation) save vs your Taijutsu Save DC or suffer the Blinded Condition'),
    h('Dazing'),
    p('Conditional Effect Your jutsu has the chance to inflict the Daze condition. Creatures affected by your jutsu must make a constitution (or wisdom, pick one at jutsu creation) save vs your Taijutsu Save DC or suffer the Daze Condition'),
    h('Deafening'),
    p('Conditional Effect Your jutsu has the chance to cause the deafened condition. Creatures affected by your jutsu must make a constitution (or wisdom, pick one at jutsu creation) save vs your Taijutsu save DC.'),
    h('Knock Back'),
    p('Your Jutsu has the chance to knock a creature back 15ft. Creatures affected by your jutsu must make a Strength saving throw vs your Jutsu Save DC. If this effect is added to a Taijutsu/Bukijutsu of C-Rank or higher, failing creatures can instead be pushed back by an additional +10 feet for each rank above D-Rank the jutsu this effect is added to is.'),
    h('Poisoning'),
    p('Conditional Effect Required Keywords: Medical Your Jutsu has the chance to inflict the poisoned Condition. Creatures affected by your jutsu must make a constitution save vs your Jutsu save DC or suffer the poisoned condition.'),
    h('Restraining'),
    p('Conditional Effect Your Jutsu has the chance to inflict the restrained condition. Creatures affected by your jutsu must make a Strength (or Dexterity or Constitution) save vs your Jutsu save DC or suffer the restrained condition.'),
    h('Delayed Effect'),
    p('Your jutsu after affecting a creature has a delayed effect that activated on the following round after this jutsu ends. Select one Effect that your jutsu currently has, other than this one. Your jutsu activates the selected effect at the beginning of either your, or the affected creature’s next turn'),
    h('Secondary Effect'),
    p('Your jutsu has multiple conditional effects built into it. You can only select this effect if you have another Conditional Effect added to your custom jutsu. Select an additional Conditional Effect adding that effect to your jutsu (This additional Conditional Effect does not cost an additional slot.). You must select one saving throw to use. Your jutsu cannot require more than 1 saving throw. You can select this effect additional times, each time being able to select an additional Conditional Effect.'),
    h('Support'),
    h('Augmentation'),
    p('Prerequisites: Chakra Molding, Self, Lasting Your Jutsu modifies your targets attacks in some way, making it more lethal, more powerful, accurate or more potent. Select one of the following; Weapon attacks or Taijutsu Attacks. This jutsu will only affect the selected type. Next choose which aspect of the chosen attack is being augmented; Attack roll or Damage roll. If Attack roll, for the duration, this jutsu increases the select attack roll by 1d4 for the duration. This bonus is increased to a d6 if added to a B-Rank or higher jutsu. By adding If Damage roll, you must add the Damage effect to this jutsu. (This does not cost an additional slot). When you do select from the following bonus damage dice pools;\n\nYou can select this effect up no more than three times. You cannot select the same combination of attack types and augmentations no matter how many times you may add this effect.'),
    h('Boosting'),
    p('Required Keywords: Self or Touch, Chakra Molding Your Jutsu modifies chance in a positive way for its targets. At Jutsu creation, select one from the following; Saving throws, Ability Checks or Skill Checks Saving Throws, Ability Checks or Skill Checks, select one of the following ability scores; Strength, Dexterity, Constitution, Intelligence, Wisdom, Charisma. This jutsu will on affect saving throws, ability checks or skill checks of the selected ability score. If Saving Throws were selected, for the duration, this jutsu boosts the select save by +1. This boost increases to +2 at B-Rank and +3 at S-Rank. If Ability Checks or Skill Checks were selected, for the duration, this jutsu boosts the select check by 1d4. This penalty increases to d6 at B-Rank and d8 at S-Rank. You can add this effect multiple times. If added a second time, you can choose to affect all Saving Throws, Ability Checks or Skill Checks (Pick one). If added a third time you can select another statistic to boost.'),
    h('Empowered Boosting'),
    p('Required Keywords: Boosting Your jutsu can boost other statistics of your target. At jutsu creation, select one of the following; Ability Score, Armor Class or speed. Ability Score. Select one of the following ability scores; Strength, Dexterity, Constitution, Intelligence, Wisdom, Charisma. Target(s) gains a boost to the chosen ability score equal to the rank this jutsu was cast at. (D-Rank: +1, C-Rank: +2, B-Rank: +3, A-Rank: +4, S-Rank: +5.) Armor Class. Target(s) gains a boost to its Armor class equal to the rank this jutsu was cast at. (D-Rank/C-Rank: +1, B-Rank/A-Rank: +3, S-Rank: +5.) Speed. Target(s) gain a boost to its speed equal to the rank this jutsu was cast at. (D-Rank: +10ft, C-Rank: +20ft, B-Rank: +30ft, A-Rank: +40ft, S-Rank: +50ft.)'),
    h('STEP FOUR: FINALIZING THE COST, NAME, AND YOUR LEGACY.'),
    p('The fourth and Final step is to clarify the cost and downtime cost of Your Jutsu, while also coming up with a memorable name. Refer to the chart below to find the Downtime cost and your jutsu’s final cost overall.'),
    t('Final jutsu rank and downtime cost', ['Associated Rank', 'Chakra Cost', 'Downtime Cost (Solo)', 'Downtime Cost (Master)'], [
      ['E-Rank', 'Special (2 Chakra)', '1', '—'],
      ['D-Rank', 'Special (4 Chakra)', '3', '2'],
      ['C-Rank', 'Special (7 Chakra)', '5', '4'],
      ['B-Rank', 'Special (12 Chakra)', '10', '8'],
      ['A-Rank', 'Special (17 Chakra)', '15', '12'],
      ['S-Rank', 'Special (25 Chakra)', '25', '20']
    ])
  ]
};
