import type { DowntimeActivity } from './model';
import { h, p, t } from './block-utils';

export const JUTSU_GENJUTSU_ACTIVITY: DowntimeActivity = {
  id: 'jutsu-genjutsu',
  tileLabel: 'Genjutsu creation',
  modalTitle: 'Genjutsu creation rules',
  blocks: [
    h('Genjutsu creation rules'),
    h('STEP TWO: GENJUTSU PREREQUISITE(S) & RESTRICTIONS'),
    p('The second step of developing your genjutsu is to figure out the base requirements, how this new Jutsu is activated regarding its Components, and whether it will be a ranged or Melee Jutsu. While selecting the Required Keywords for your Jutsu, keep in mind Genjutsu have Mandatory Components. If your jutsu does not have a Requirement in the list (Such as in the Requirement Keywords) then you may skip that Step. But most Jutsu encompass all or some of these Categories.'),
    h('Hijutsu'),
    p('By selecting this requirement keyword your Genjutsu gains the Hijutsu Keyword, and counts as being a Clan Jutsu for you. You cannot select this Keyword if you are non-Clan.'),
    h('Medical'),
    p('By selecting this requirement keyword your Genjutsu will gain the Medical Keyword.'),
    h('Fuinjutsu'),
    p('By selecting this requirement keyword your Genjutsu will gain the Fuinjutsu Keyword.'),
    h('Nature Release'),
    p('By selecting this requirement keyword your Genjutsu will gain one or many Nature Release Keywords. This does not grant your Genjutsu the ability to deal Elemental damage, but instead potentially benefit from other class or clan features or feats.'),
    h('Required Feature'),
    p('By selecting this requirement keyword, you are required to be able to benefit from a Clan or Class feature that has a number of limited uses and recharges on a short or long rest to use this Genjutsu. You cannot add this to E-Ranks The chosen feature, must be one that has to be activated by the user. The chosen feature cannot be something passive like Unarmed Combat from Taijutsu Specialist, or Advanced Nature Transformation from the Sarutobi Clan. The feature must require activation of some sort from the player. Regardless of the feature chosen, when this jutsu is cast, a use of the feature is also spent as part of the cost of casting this jutsu. You do not gain the benefits of casting such a resource.'),
    h('Hand Seals (HS)'),
    p('By Selecting this Component Keyword, your genjutsu requires you to have 1 hand free in order to weave handseals.'),
    h('Chakra Molding (CM)'),
    p('By selecting Genjutsu as your jutsu type, you have to take this keyword for your jutsu.'),
    h('Chakra Seals (CS)'),
    p('By Selecting this Component Keyword, your genjutsu requires you to have 1 hand free in order to create the chakra seals needed in order to manifest the required jutsu. In order to utilize Fuinjutsu of any type, you must add this Component Keyword.'),
    h('Weapon (W)'),
    p('By Selecting this Component Keyword, your genjutsu requires you to have a weapon available to you and within reach. Select one weapon type that this Genjutsu requires in order to function. In order for you to select this keyword the range of your jutsu must either be Self, or Touch.'),
    t('Prerequisites', ['Prerequisite Keywords', 'Bonus Effect Slots'], [
      ['Hijutsu', '+0'],
      ['Medical', '+0'],
      ['Fuinjutsu', '+0'],
      ['Nature Release', '+0'],
      ['Required Feature (Short Rest)', '+1'],
      ['Required Feature (Long Rest)', '+2']
    ]),
    p('Medical +0 Fuinjutsu +0 Nature Release +0 Required Feature (Short Rest) +1 Required Feature (Long Rest) +2'),
    t('Components', ['Component Keyword', 'Notes'], [
      ['Hand Seals (HS)', '(Mandatory for all created Ninjutsu / Genjutsu)'],
      ['Chakra Molding (CM)', '(Mandatory with Nature Release and Medical; mandatory for all Genjutsu)'],
      ['Chakra Seals (CS)', '(Mandatory with Fuinjutsu)'],
      ['Mobility (M)', '—'],
      ['Weapon (W)', '—'],
      ['Ninja Tools (NT)', '—']
    ]),
    p('Chakra Molding (CM) - (Mandatory for all created Genjutsu) Chakra Seals (CS) - (Mandatory with Fuinjutsu) Mobility (M) - Weapon (W) - Ninja Tools (NT) -'),
    h('Ninja Tools (NT)'),
    p('By Selecting this Component Keyword, your genjutsu requires you to have a Ninja tool available to you and within reach. Select one Ninja Tool that this Genjutsu requires in order to function. In order for you to select this keyword the range of your jutsu must either be Self, or Touch.'),
    h('Visual'),
    p('Jutsu with the Visual Keyword, are genjutsu that tricks the targets visual perception. Creatures with True sight or Blindness are immune to jutsu with this keyword. Chakra sight provides advantage against Jutsu with only this keyword.'),
    h('Tactile'),
    p('Jutsu with the Tactile keyword, are genjutsu that tricks the targets perception of touch (both pleasure and pain). This keyword is needed in order for a Genjutsu to deal damage.'),
    h('Auditory'),
    p('Jutsu with the Auditory keyword, are genjutsu that tricks the targets personal perception of sound. Deafness provides immunity to jutsu with only this keyword.'),
    h('Inhaled'),
    p('Your Genjutsu has a range greater than 5 feet base. Your Genjutsu will be able to travel over a distance to interact with your target creature or area. You must make a Ranged Genjutsu attack roll to score a hit with this Range.'),
    h('Unaware'),
    p('Jutsu with the Unaware Keyword, are genjutsu that completely ekes by a creatures ability to discern the real from fake. These Genjutsu are subtle enough to not be noticeable and requires a Wisdom (Illusions) check vs the DC of the Genjutsu used, to become fully aware of a single Genjutsu affecting you.'),
    h('Self'),
    p('Your Genjutsu has a range of self. This Genjutsu either will only affect you, or use you as the center or origination of its effect radius/shape. Select this range if your jutsu will do either of these things.'),
    h('Touch'),
    p('Your Genjutsu has a range of Touch (5 Feet). Your Genjutsu will only be able to apply its effects if you are able to physically touch your target creature. You must make a Melee Genjutsu attack roll to score a hit with this Range.'),
    h('Ranged'),
    p('Your Genjutsu has a range greater than 5 feet base. Your Genjutsu will be able to travel over a distance to interact with your target creature or area. You must make a Ranged Genjutsu attack roll to score a hit with this Range. If this range is added to a Genjutsu of C-Rank, increase the maximum possible range to 60 feet. If this range is added to a Genjutsu of A-Rank or higher, the maximum possible range is increased to 120 feet.'),
    h('Critical Success'),
    p('A creature who passes your Genjutsu save DC by 5 or more. This creature always passes and suffers no additional effects. If the chosen Jutsu is D-Rank, the target becomes immune for 10 minutes, if C-Rank, then only 1 Minute, if B-Rank or higher, they cannot be affected again for at least 1 of your turns.'),
    h('Success'),
    p('When a creature passes your Genjutsu save DC but not exceeding 5 or more.'),
    h('Failure'),
    p('When a creature fails your Genjutsu save DC but not exceeding -5 or more.'),
    h('Critical Failure'),
    p('When a creature fails your Genjutsu save DC by -5 or more. This creature always suffers a greater effect. If Damage increase the damage die by 1 step or damage die by +2. If a Conditional Effect that can have more than 1 rank, increase the number of inflicted ranks by +1. If Hindering, increase the penalty die by 1 step, up to a d12.'),
    t('Sensory keywords', ['Keyword', 'Requirement(s)'], [
      ['Visual', '—'],
      ['Tactile', 'Mandatory, if it deals Damage'],
      ['Auditory', '—'],
      ['Inhaled', 'Ninja Tools (NT)'],
      ['Unaware', 'Costs 1 Effect Slot']
    ]),
    p('Requirement(s) Visual - Tactile Mandatory, if it deals Damage Auditory - Inhaled Ninja Tools (NT) Unaware Costs 1 Effect Slot\n\n\n\nNotes Self - Touch (5 feet) - Ranged Up to 30 feet'),
    t('Tiers of success', ['Tier', 'Requirement(s)', 'Bonus Effect Slots'], [
      ['Critical Success', 'Mandatory, if Requiring a Save', 'If no Critical Success, -1'],
      ['Success', 'Mandatory, if Requiring a Save', '—'],
      ['Failure', 'Mandatory, if Requiring a Save', '—'],
      ['Critical Failure', 'Optional', 'If no Critical Failure, +1']
    ]),
    p('Bonus Effect Slots Critical Success Mandatory, if Requiring a Save If no Critical Success, -1 Success Mandatory, if Requiring a Save - Failure Mandatory, if Requiring a Save - Critical Failure Optional If no Critical Failure, +1'),
    h('STEP THREE: EFFECTS'),
    p('The third Step of jutsu creation comes down to selecting your jutsu’s damage type, The final range of your jutsu based on the range selected and what sort of effects it may have.\n\n\n\nAll Genjutsu follow a certain theme or archetype that they follow. Most jutsu fall into 4 different forms of casting. Either Offensive, Defensive, Control or Support. To describe these categories for the purposes of jutsu creation.\n\n\n\n• Offensive. Effects that deal damage, or attempts to inflict conditions or negative effects onto other creatures.\n\n\n\n• Defensive. Effects that mitigate damage in a number of ways; such as Damage reduction, resistance, immunity, temporary hit points.\n\n\n\n• Control. Effects that manipulate or impact other creatures ability to act or impose penalties of any type onto the target, such as attack/damage penalties, saving throw penalties, speed penalties, etc.\n\n\n\n• Support. Effects that aid yourself or other allied creatures by providing positive benefits, such as healing, bonuses to hit or damage, etc.\n\n\n\nDecide on no more than 2 of the above Genjutsu Types. When you do, you can only choose effects from their given categories. While creating your Jutsu, keep in mind each effect you add will cost 1 Effect Slot based on the rank of the jutsu you are creating. Below you will find effect that doesn’t fit any one genjutsu type, but instead enables them all.'),
    h('Area'),
    p('Your Jutsu gains an area of effect in the shape of one of the following: 20ft radius, 15ft Cone, 20ft Cube, 20ft Cylinder or 30ft Line. Creatures must succeed one of the following; (Intelligence, Wisdom or Charisma) save vs your Genjutsu Save DC. If your Jutsu requires any other Saving throw to avoid an additional Condition, this save becomes the jutsu’s base save omitting all other saving throws that other effects may ask for. This does not count for Effects Selected with " Tertiary Effect". Reduce the Damage Die by 1, to a minimum of 1. Creatures suffer half damage and no Conditional effects on a successful save. If this effect is added to a Genjutsu of C-Rank or higher, increase the shape by 5 feet for each rank above D-Rank, the jutsu this effect is added to is.'),
    h('Delayed Effect'),
    p('Your jutsu after affecting a creature has a delayed effect that activated on the following round after this jutsu ends. Select one effect that your jutsu currently has, other than this one. Your jutsu activates the selected effect at the beginning of either your, or the affected creature’s next turn (Pick one when creating this jutsu)'),
    h('Lasting'),
    p('Your Jutsu increases its duration from Instant Concentration, up to 1 minute. If you apply this effect an additional time, the duration is increased to Concentration, up to 10 minutes. If you apply this effect, to a jutsu whose current casting time is a Reaction, its duration instead becomes 1 Round. If this effect is added to a jutsu with a Conditional Effect, affected creatures can attempt to remake their saving throws at the end of each of their turns to end this Jutsu\'s effects on them.'),
    h('Speedy'),
    p('Your Jutsu can be cast at a significantly faster speed than most others. The cast time of this Jutsu becomes a Bonus action. If your jutsu deals damage or heals creatures, reduce the damage or healing die by 1. You can take this effect a second time, changing the casting time to a Reaction, if you do reduce your Damage die by 2.'),
    h('Failure In Success'),
    p('Your Jutsu imposes a partial effect even if a creature passes the saving throw (But not critically pass). Pick one of the following. If Damage, reduce the damage dice by half (rounded down) If a Conditional Effect, affected creatures gains no more than 1 rank of a single chosen condition, for up to 1 turn. If Hindering, affected creature suffers half of the listed effect or the duration is reduced to 1 turn. Pick 1.'),
    h('Upcast'),
    p('Your Jutsu can be upcast from its current rank, increasing one of its current effects potency per rank upcast. Pick one of the following. If Damage, Shielding or Healing, increase the damage, healing or shielding the jutsu does by 2 damage/healing/shielding die, per rank upcast. (Pick one) If a Conditional Effect, increase the number of ranks of one of the chosen conditions this jutsu applies by +1, per rank upcast.'),
    h('Unavoidable'),
    p('Your Jutsu does not require you to make an attack roll, instead always having the chance to hit your target. Select a target creature within range that you can sense with one of the following senses. Target Creature must make an (Intelligence Wisdom or Charisma) save vs your Genjutsu Save DC. (Choose the saving throw at jutsu creation). This saving throw supersedes all other saving throw options provided by other effects. When you have added all affects you want to your Genjutsu, this effects Saving throw becomes the overall saving throw of your Genjutsu.'),
    h('Offensive'),
    h('Critical'),
    p('Required Keyword/Effects: Tactile (Keyword), Damage (Effect) Increase this jutsu’s critical threat range by +1. You can add this effect an additional time, increasing this jutsu’s critical threat range by an additional +1 for each time you add this effect, after the first.'),
    h('Damage'),
    p('Required Keywords: Tactile This Genjutsu deals Psychic damage. Select one of the following damage die that your jutsu has based on its rank. Jutsu that deals more types of damage at once splits its damage evenly between each available damage die.'),
    t('Genjutsu damage die pools by rank', ['Rank', 'Damage die pools'], [
      ['D-Rank', '5d4, 4d6, 3d8, 2d10'],
      ['C-Rank', '8d4, 5d6, 4d8, 3d10, 2d12'],
      ['B-Rank', '12d4, 8d6, 6d8, 4d10, 3d12'],
      ['A-Rank', '16d4, 12d6, 9d8, 7d10, 5d12'],
      ['S-Rank', '20d4, 15d6, 12d8, 9d10, 7d12']
    ]),
    h('Empowered Damage'),
    p('Required Effects: Damage Your Jutsu increases its overall damage potential. Increase your damage die by 1. This effect can be taken up to 3 additional times after the first.'),
    h('Multiple Strikes'),
    p('Required Effects: Damage Your jutsu grants you more than a single Attack Roll. Increase the number of attacks your jutsu makes by +1. Split your damage dice between the attacks evenly. You can take this effect up to two times total.'),
    h('Powerful Offense'),
    p('Required Effects: Damage Your Jutsu is magnified further. When you would roll your jutsu’s damage, you add your Genjutsu ability modifier to your first damage roll. You can take this effect an additional time, gaining the ability to add your ability modifier to all damage rolls made with this jutsu.'),
    h('Defensive'),
    h('Empowered Shielding'),
    p('Required Keywords: Shielding Your Jutsu increases its overall defensive potential. Increase your shielding die by 2. This effect can be taken one additional time.'),
    h('Resistance'),
    p('Required Keywords: Tactile Your Jutsu grants either yourself or the target creature (your choice during creation) with resistance to a given damage type or Condition. Select between Damage or Condition. Once your choice is made, select one from the following list based on your previous decision. Damage: Psychic Condition: Blinded, deafened, dazed, incapacitated, slowed, berserk, fear, concussed, confused, maddened, dazzled. This Jutsu\'s target gains resistance to the chosen damage type or condition for this Jutsu\'s duration. This effect can be taken multiple times. Each time you select it, pick a different damage type or condition.'),
    h('Shielding'),
    p('Required Effects: Lasting, Tactile Your Jutsu grants temporary hit points to its target. Select one of the following dice pools that your jutsu has based on its rank. This pool determined how much temporary hit points this jutsu grants.'),
    h('Control'),
    p('Genjutsu can have up to Two Conditional effects, selecting one saving throw as the basis of this jutsu. This can be increased to three with Tertiary Effect or Delayed Effect. Tertiary effect and Delayed effect do not stack and cannot be taken together in any combination. If an effect you select would inflict a condition on a creature and you don’t have the Lasting effect on your jutsu and the condition inflicted has no discernable duration, its duration becomes 1 Round.'),
    h('Blinding'),
    p('Conditional Effect Required Keywords: Visual Your jutsu has the chance to inflict the Blinded condition for the duration. Creatures affected by your jutsu must make an (Intelligence, Wisdom or Charisma) save vs your Jutsu Save DC. (Choose the saving throw at jutsu Creation).'),
    h('Berserker'),
    p('Required Keywords: Visual or Auditory or Inhaled Your Justus has the chance to inflict the Berserk condition for the duration. Creatures affected by your jutsu must an (Intelligence, Wisdom or Charisma) save vs your Genjutsu Save DC. (Choose the saving throw at Jutsu creation).'),
    h('Charming'),
    p('Required Keywords: Visual or Auditory or Inhaled Your Justus has the chance to inflict the Charmed condition for the duration. Creatures affected by your jutsu must an (Intelligence, Wisdom or Charisma) save vs your Genjutsu Save DC. (Choose the saving throw at Jutsu creation).'),
    h('Concussive'),
    p('Required Keywords: Visual or Auditory or Inhaled Your Justus has the chance to inflict the Concussed condition for the duration. Creatures affected by your jutsu must an (Intelligence, Wisdom or Charisma) save vs your Genjutsu Save DC. (Choose the saving throw at Jutsu creation).'),
    h('Conditional'),
    p('Your Jutsu can only be cast targeting a single creature who is currently suffering from a condition already. If this jutsu is cast targeting a creature not suffering a select condition, they are immune to its effects. Select one Condition from the following list: Berserk, blinded, charmed, concussed, confused, dazzled, deafened, frightened, incapacitated, paralyzed, poisoned, slowed or maddened. Select two additional Control effects, adding them to this jutsu, at no additional slot cost. The two effects adding must be different from one another and cannot be an effect already added to this jutsu.'),
    h('Deafening'),
    p('Conditional Effect Required Keywords: Auditory Your jutsu has the chance to cause the Deafened condition for the duration. Creatures affected by your jutsu must an (Intelligence, Wisdom or Charisma) save vs your Genjutsu Save DC. (Choose the saving throw at Jutsu creation).'),
    h('Delayed Effect'),
    p('Your jutsu after affecting a creature has a delayed effect that activated on the following round after this jutsu ends. Select one effect that your jutsu currently has, other than this one. Your jutsu activates the selected effect at the beginning of either your, or the affected creature’s next turn.'),
    h('Empowered Hindering'),
    p('Required Keywords: Hindering Your jutsu can hinder other statistics of your target. At jutsu creation, select one of the following; Ability Score, Armor Class, Speed, Damage. Ability Score. Select one of the following ability scores; Strength, Dexterity, Constitution, Intelligence, Wisdom, Charisma. On a failed save the target(s) suffers a penalty to the chosen ability score equal to the rank this jutsu was cast at. (D-Rank: -1, C-Rank: -2, B-Rank: -3, A-Rank: -4, S-Rank: -5.) Armor Class. On a failed save the target(s) suffers a penalty to its Armor class equal to the rank this jutsu was cast at. (D-Rank: -1, C-Rank: -2, B-Rank: -3, A-Rank: -4, S-Rank: -5.) Speed. On a failed save the target(s) suffers a penalty to its speed equal to the rank this jutsu was cast at. (D-Rank: -10ft, C-Rank: -20ft, B-Rank: -30ft, A-Rank: -40ft, S-Rank: -50ft.) Damage. On a failed save the target(s) suffers a penalty to its damage dealt equal to the rank this jutsu was cast at. (D-Rank: -1 damage die, C-Rank: -2 damage die, B-Rank: -3 damage die, A-Rank: -4 damage die, S-Rank: -5 damage die.)'),
    h('Frightening'),
    p('Conditional Effect Your Jutsu has the chance to inflict 1 rank of the Fear Condition for the duration.. Creatures affected by your jutsu must an (Intelligence, Wisdom or Charisma) save vs your Genjutsu Save DC. (Choose the saving throw at Jutsu creation).'),
    h('Hindering'),
    p('Required Keywords: Tactile Your Jutsu modifies chance in a negative way for its targets. At Jutsu creation, select one from the following; Attack Rolls, Saving throws, Ability Checks or Skill Checks Attack Rolls, select one of the following; Weapon attacks, Ninjutsu Attacks, Taijutsu Attacks or Genjutsu Attacks. This jutsu will only affect the selected type. Saving Throws, Ability Checks or Skill Checks, select one of the following ability scores; Strength, Dexterity, Constitution, Intelligence, Wisdom, Charisma. This jutsu will on affect saving throws, ability checks or skill checks of the selected ability score. Next, if Attack Rolls were selected, for the duration, this jutsu penalizes the select attack roll by 1d4 for the duration. This bonus is increased to a d6 at B-Rank and a d8 at S-Rank. If Saving Throws were selected, for the duration, this jutsu penalizes the select save by -1. This penalty increases to -3 at B-Rank and -5 at S-Rank. If Ability Checks or Skill Checks were selected, for the duration, this jutsu penalizes the select check by 1d4. This penalty increases to d6 at B-Rank and d8 at S-Rank. You can add this effect multiple times. If added a second time, you can choose to affect all Attack Rolls, Saving Throws, Ability Checks or Skill Checks (Pick one). If added a third time you can select another statistic to penalize. If added a fourth time creatures do not get to remake their saving throws to end this jutsu’s effects.'),
    h('Restraining'),
    p('Conditional Effect Required Keywords: Any Sensory Keyword Your Jutsu has the chance to inflict the Restrained Condition for the duration.. Creatures affected by your jutsu must an (Intelligence, Wisdom or Charisma) save vs your Genjutsu Save DC. (Choose the saving throw at Jutsu creation).'),
    h('Sealing'),
    p('Conditional Effect Required Keywords: Fuinjutsu, Touch, Chakra Seals (CS), Lasting Your Jutsu seals away a creatures memories or thoughts. Creatures affected by your jutsu must make a Charisma saving throw. On a failed save, the target is marked with a single seal of your description for the duration. This seal does one of the following, of your choice. (Choose during jutsu creation.) Memory Seal. While bound with this seal, the target suffers forgets how to cast a number of jutsu of your choice equal to the rank this jutsu is cast; (D-Rank/C-Rank: 1, B-Rank/A-Rank: 2, S-Rank: 3) Thought Seal. While bound with this seal, the target cannot maintain concentration on a number of jutsu equal to the rank this jutsu is cast; (D-Rank/C-Rank/ B-Rank: 1, A-Rank/S-Rank: 2) Emotional Seal. While bound with this seal, the target cannot target a creature of your choice with any jutsu for the duration. This Keyword can be taken up to 3 times. Each time you take this keyword, select an additional effect.'),
    h('Tertiary Effect'),
    p('Your jutsu has multiple conditional effects built into it. You can only select this effect if you have two Conditional Effect added to your custom jutsu. Select an additional Conditional Effect adding that effect to your jutsu (This additional Conditional Effect does not cost an additional slot.). You must select one saving throw to use. Your jutsu cannot require more than 1 saving throw. You can select this effect additional times, each time being able to select an additional Conditional Effect.'),
    h('Slowing'),
    p('Conditional Effect Required Keywords: Any Sensory Keyword Your Jutsu has the chance to inflict 1 rank of the Slow Condition for the duration.. Creatures affected by your jutsu must an (Intelligence, Wisdom or Charisma) save vs your Genjutsu Save DC. (Choose the saving throw at Jutsu creation).'),
    h('Weakening'),
    p('Conditional Effect Required Keywords: Any Sensory Keyword Your Jutsu has the chance to inflict 1 rank of the Weakened Condition for the duration. Creatures affected by your jutsu must an (Intelligence, Wisdom or Charisma) save vs your Genjutsu Save DC. (Choose the saving throw at Jutsu creation).'),
    h('Maddening'),
    p('Conditional Effect Required Keywords: Any Sensory Keyword Your Jutsu has the chance to inflict the Maddened Condition for the duration. Creatures affected by your jutsu must an (Intelligence, Wisdom or Charisma) save vs your Genjutsu Save DC. (Choose the saving throw at Jutsu creation).'),
    h('Concussive'),
    p('Conditional Effect Required Keywords: Any Sensory Keyword Your Jutsu has the chance to inflict 1 rank of the Concussed Condition for the duration. Creatures affected by your jutsu must an (Intelligence, Wisdom or Charisma) save vs your Genjutsu Save DC. (Choose the saving throw at Jutsu creation).'),
    h('Dazzling'),
    p('Conditional Effect Required Keywords: Any Sensory Keyword Your Jutsu has the chance to inflict 1 rank of the Dazzled Condition for the duration. Creatures affected by your jutsu must an (Intelligence, Wisdom or Charisma) save vs your Genjutsu Save DC. (Choose the saving throw at Jutsu creation).'),
    h('Confusing'),
    p('Conditional Effect Required Keywords: Any Sensory Keyword Your Jutsu has the chance to inflict 1 rank of the Confused Condition for the duration. Creatures affected by your jutsu must an (Intelligence, Wisdom or Charisma) save vs your Genjutsu Save DC. (Choose the saving throw at Jutsu creation).'),
    h('Mind Control'),
    p('Required Keywords: Visual, Auditory or Inhaled Special Limitation: B-Rank and above. Your Justus has the chance to glamor a creature, granting you control over their thoughts or actions. Creatures affected by your jutsu must an Intelligence, Wisdom or Charisma save vs your Genjutsu Save DC. (Choose the saving throw at Jutsu creation, this cannot be changed later). On a failed save, the target is mentally dominated in a way of your description for the duration. This domination causes one of the following effects to take place. (Choose during jutsu creation.) Glamor. The target acts in one way of your choice that isn’t directly harmful to itself, by spending its action on its turn. This jutsu then ends. Overwrite. The target has 10 minutes’ worth of memory overwritten. Target creatures becomes immune to this jutsu if they are targeted while in combat or combat would begin around them. Memory that is overwritten becomes permanently changed within 24 hours of its casting. This effect can be nullified/ended if dispelled at any time after this Jutsu\'s casting. Disable. The target becomes unable to take an either a Bonus Action or Reaction (your choice) to perform a specific task, such as cast a jutsu, use a feature or trait, active an item, interact with the environment etc. Make your select when this jutsu is created.'),
    h('Displacement'),
    p('Required Keywords: Visual Your Justus has the chance to mentally displace a creature, making them believe they are someone they are not. Creatures affected by your jutsu must an Intelligence, Wisdom or Charisma save vs your Genjutsu Save DC. (Choose the saving throw at Jutsu creation, this cannot be changed later). On a failed save, you choose where the target believes itself to be for the duration.'),
    h('Support'),
    h('Augmentation'),
    p('Prerequisites: Chakra Molding, Self or Touch (Range), Lasting Your Jutsu modifies your targets attacks in some way, making it more lethal, more powerful, accurate or more potent. Select one of the following; Weapon attacks, Ninjutsu Attacks, Taijutsu Attacks or Genjutsu Attacks. This jutsu will only affect the selected type. Next choose which aspect of the chosen attack is being augmented; Attack roll or Damage roll. If Attack roll, for the duration, this jutsu increases the select attack roll by 1d4 for the duration. This bonus is increased to a d6 if added to a B-Rank or higher jutsu. By adding If Damage roll, you must add the Damage effect to this jutsu. (This does not cost an additional slot). When you do select from the following bonus damage dice pools;\n\nYou can select this effect up no more than three times. You cannot select the same combination of attack types and augmentations no matter how many times you may add this effect.'),
    h('Boosting'),
    p('Required Keywords: Self or Touch, Chakra Molding, Tactile Your Jutsu modifies chance in a positive way for its targets. At Jutsu creation, select one from the following; Saving throws, Ability Checks or Skill Checks Saving Throws, Ability Checks or Skill Checks, select one of the following ability scores; Strength, Dexterity, Constitution, Intelligence, Wisdom, Charisma. This jutsu will on affect saving throws, ability checks or skill checks of the selected ability score. If Saving Throws were selected, for the duration, this jutsu boosts the select save by +1. This boost increases to +2 at B-Rank and +3 at S-Rank. If Ability Checks or Skill Checks were selected, for the duration, this jutsu boosts the select check by 1d4. This penalty increases to d6 at B-Rank and d8 at S-Rank. You can add this effect multiple times. If added a second time, you can choose to affect all Saving Throws, Ability Checks or Skill Checks (Pick one). If added a third time you can select another statistic to boost.'),
    h('Empowered Boosting'),
    p('Required Keywords: Boosting Your jutsu can boost other statistics of your target. At jutsu creation, select one of the following; Ability Score, Armor Class, Speed, Damage. Ability Score. Select one of the following ability scores; Strength, Dexterity, Constitution, Intelligence, Wisdom, Charisma. Target(s) gains a boost to the chosen ability score equal to the rank this jutsu was cast at. (D-Rank: +1, C-Rank: +2, B-Rank: +3, A-Rank: +4, S-Rank: +5.) Armor Class. Target(s) gains a boost to its Armor class equal to the rank this jutsu was cast at. (D-Rank/C-Rank: +1, B-Rank/A-Rank: +3, S-Rank: +5.) Speed. Target(s) gain a boost to its speed equal to the rank this jutsu was cast at. (D-Rank: +10ft, C-Rank: +20ft, B-Rank: +30ft, A-Rank: +40ft, S-Rank: +50ft.) Damage. Target(s) gain a boost to its damage dealt equal to the rank this jutsu was cast at. (D-Rank: +1 damage die, C-Rank: +2 damage die, B-Rank: +3 damage die, A-Rank: +4 damage die, S-Rank: +5 damage die.)'),
    h('STEP FOUR: FINALIZING THE COST, NAME, AND YOUR LEGACY.'),
    p('The fourth and Final step is to clarify the cost and downtime cost of Your Jutsu, while also coming up with a memorable name. Refer to the chart below to find the Downtime cost and your jutsu’s final cost overall.'),
    t('Final jutsu rank and downtime cost', ['Associated Rank', 'Chakra Cost', 'Downtime Cost (Solo)', 'Downtime Cost (Master)'], [
      ['E-Rank', 'Special (2 Chakra)', '1', '—'],
      ['D-Rank', 'Special (4 Chakra)', '3', '2'],
      ['C-Rank', 'Special (7 Chakra)', '5', '4'],
      ['B-Rank', 'Special (12 Chakra)', '10', '8'],
      ['A-Rank', 'Special (17 Chakra)', '15', '12'],
      ['S-Rank', 'Special (25 Chakra)', '25', '20']
    ])
  ]
};
