import type { DowntimeActivity } from './model';
import { h, p, t } from './block-utils';

export const JUTSU_NINJUTSU_ACTIVITY: DowntimeActivity = {
  id: 'jutsu-ninjutsu',
  tileLabel: 'Ninjutsu creation',
  modalTitle: 'Ninjutsu creation rules',
  blocks: [
    h('Ninjutsu creation rules'),
    h('STEP TWO: NINJUTSU PREREQUISITE(S) & RESTRICTIONS'),
    p('The second step of developing your ninjutsu is to figure out the base prerequisites, how this new Jutsu is activated regarding its Components, and whether it will be a ranged or melee Jutsu. While selecting the required keywords for your Jutsu, keep in mind select jutsu types have mandatory Components and regardless of what type of jutsu you make your jutsu must have at least 1 Component. If your jutsu does not have a requirement in the list (Such as in the Prerequisite Keywords) then you may skip that Step.'),
    h('Hijutsu'),
    p('By selecting this requirement keyword your Ninjutsu gains the Hijutsu Keyword, and counts as being a Clan Jutsu for you. You cannot select this Keyword if you are non-Clan.'),
    h('Medical'),
    p('By selecting this requirement keyword your Ninjutsu will gain the Medical Keyword.'),
    h('Fuinjutsu'),
    p('By selecting this requirement keyword your Ninjutsu will gain the Fuinjutsu Keyword.'),
    h('Nature Release'),
    p('By selecting this requirement keyword your Ninjutsu will gain one or many Nature Release Keywords. When you select a nature release, your jutsu gains the nature releases special mechanics; Earth Release: Stalwart. If your jutsu summons a construct or has any effects that grants the target resistance or immunity, it gains that effect vs cold damage, and one additional damage type of your choice excluding Psychic and Lightning. Wind Release: Swirl. Creatures who would fail their saving throw, spreads all Elemental conditions currently affecting them around to all creatures, excluding the caster within 5 feet of them. Hostile creatures within 5 feet of the failing one gains 1 rank of all elemental conditions currently affecting it. Fire Release: Blaze. For every dice of fire damage this jutsu deals, it gains +1 fire damage. Water Release: Serenity. If used near a sufficient source of water, reduce the chakra cost of this jutsu by 2. Lightning Release: Overcharge. When you cast this jutsu, as a bonus action or reaction, you can overcharge its effects. When you do, if this jutsu inflicts a condition, increase the number of ranks it applies by +1 or if this jutsu deals damage, increase the damage this jutsu deals by +2 damage die.'),
    h('Required Feature'),
    p('By selecting this requirement keyword, you are required to be able to benefit from a Clan or Class feature that has a number of limited uses and recharges on a short or long rest to use this Ninjutsu. You cannot add this to E-Ranks The chosen feature, must be one that has to be activated by the user. The chosen feature cannot be something passive like Unarmed Combat from Taijutsu Specialist, or Advanced Nature Transformation from the Sarutobi Clan. The feature must require activation of some sort from the player. Regardless of the feature chosen, when this jutsu is cast, a use of the feature is also spent as part of the cost of casting this jutsu. You do not gain the benefits of spending said resource.'),
    h('Hand Seals (HS)'),
    p('By Selecting this Component Keyword, your ninjutsu requires you to have 1 hand free in order to weave handseals. Hand Seals are mandatory when creating a Ninjutsu.'),
    h('Chakra Molding (CM)'),
    p('By selecting this Component Keyword, your ninjutsu requires you to mold chakra in order to utilize it. In order to utilize a Nature Release of any type, you must add this Component Keyword.'),
    t('Components', ['Component Keyword', 'Notes'], [
      ['Hand Seals (HS)', '(Mandatory for all created Ninjutsu / Genjutsu)'],
      ['Chakra Molding (CM)', '(Mandatory with Nature Release and Medical; mandatory for all Genjutsu)'],
      ['Chakra Seals (CS)', '(Mandatory with Fuinjutsu)'],
      ['Mobility (M)', '—'],
      ['Weapon (W)', '—'],
      ['Ninja Tools (NT)', '—']
    ]),
    p('Chakra Molding (CM) - (Mandatory with Nature Release and Medical) Chakra Seals (CS) - (Mandatory with Fuinjutsu) Mobility (M) - Weapon (W) - Ninja Tools (NT) -'),
    t('Prerequisites', ['Prerequisite Keywords', 'Bonus Effect Slots'], [
      ['Hijutsu', '+0'],
      ['Medical', '+0'],
      ['Fuinjutsu', '+0'],
      ['Nature Release', '+0'],
      ['Required Feature (Short Rest)', '+1'],
      ['Required Feature (Long Rest)', '+2']
    ]),
    p('Medical +0 Fuinjutsu +0 Nature Release +0 Required Feature (Short Rest) +1 Required Feature (Long Rest) +2'),
    h('Chakra Seals (CS)'),
    p('By Selecting this Component Keyword, your ninjutsu requires you to have 1 hand free in order to create the chakra seals needed in order to manifest the required jutsu. In order to utilize Fuinjutsu of any type, you must add this Component Keyword.'),
    h('Mobility (M)'),
    p('By Selecting this Component Keyword, your ninjutsu requires you to have at least 5 feet of movement available to you. While your jutsu doesn’t spend this movement, it requires you to be able to move your body freely.'),
    h('Weapon (W)'),
    p('By Selecting this Component Keyword, your ninjutsu requires you to have a weapon available to you and within reach. Select one weapon type that this Ninjutsu requires in order to function.'),
    h('Ninja Tools (NT)'),
    p('By Selecting this Component Keyword, your ninjutsu requires you to have a Ninja tool available to you and within reach. Select one Ninja Tool that this Ninjutsu requires in order to function. In order for you to select this keyword the range of your jutsu must either be Self, or Touch.'),
    h('Self'),
    p('Your Ninjutsu has a range of self. This Ninjutsu either will only affect you, or use you as the center or origination of its effect radius/shape. Select this range if your jutsu will do either of these things.'),
    h('Touch'),
    p('Your Ninjutsu has a range of Touch (5 Feet). Your ninjutsu will only be able to apply its effects if you are able to physically touch your target creature. You must make a Melee Ninjutsu attack roll to score a hit with this Range.'),
    h('Ranged'),
    p('Your Ninjutsu has a range greater than 5 feet base. Your ninjutsu will be able to travel over a distance to interact with your target creature or area. You must make a Ranged Ninjutsu attack roll to score a hit with this Range. If this range is added to a Ninjutsu of C-Rank, increase the maximum possible range to 60 feet. If this range is added to a Ninjutsu of A-Rank or higher, the maximum possible range is increased to 120 feet.'),
    h('STEP THREE: EFFECTS'),
    p('The third Step of jutsu creation comes down to selecting your jutsu’s effects, using the list provided below. All jutsu are built using a combination of different effects with each effect having an associated Saving throw, damage type or special ability attached to it.\n\n\n\nAll ninjutsu follow a certain theme or archetype that they follow. Most jutsu fall into 4 different forms of casting. Either Offensive, Defensive, Control or Support. To describe these categories for the purposes of jutsu creation.\n\n\n\n• Offensive. Effects that deal damage, or attempts to inflict conditions or negative effects onto other creatures.\n\n\n\n• Defensive. Effects that mitigate damage in a number of ways; such as Damage reduction, resistance, immunity, temporary hit points.\n\n\n\n• Control. Effects that manipulate or impact other creatures ability to act or impose penalties of any type onto the target, such as attack/damage penalties, saving throw penalties, speed penalties, etc.\n\n\n\n• Support. Effects that aid yourself or other allied creatures by providing positive benefits, such as healing, bonuses to hit or damage, etc.\n\n\n\nDecide on no more than 2 of the above Ninjutsu Types. When you do, you can only choose effects from their given categories. While creating your Jutsu, keep in mind each effect you add will cost 1 Effect Slot based on the rank of the jutsu you are creating. Below you will find effect that doesn’t fit any one ninjutsu type, but instead enables them all.'),
    h('Area'),
    p('Your Jutsu gains an area of effect in the shape of one of the following: 10ft radius, 20ft Cone, 15ft Cube, 20ft Cylinder or 30ft Line. Creatures must succeed one of the following; (Strength, Dexterity or Constitution) save vs your Ninjutsu Save DC. If your Jutsu requires any other Saving throw to avoid an additional Condition, this save becomes the jutsu’s base save omitting all other saving throws that other effects may ask for. This does not count for Effects Selected with "Secondary Effect". Reduce the Damage Die by 1, to a minimum of 1. Creatures suffer half damage and no Conditional effects on a successful save. If this effect is added to a Ninjutsu of C-Rank or higher, increase the shape by 5 feet for each rank above D-Rank, the jutsu this effect is added to is.'),
    h('Clash'),
    p('Your Jutsu gains the Ability to clash with other Jutsu with the Clash Keyword.'),
    h('Delayed Effect'),
    p('Your jutsu after affecting a creature has a delayed effect that activated on the following round after this jutsu ends. Select one effect that your jutsu currently has, other than this one. Your jutsu activates the selected effect at the beginning of either your, or the affected creature’s next turn (Pick one when creating this jutsu)'),
    t('Ranges', ['Range Keywords', 'Notes'], [
      ['Self', '—'],
      ['Touch (5 feet)', '—'],
      ['Ranged', 'Up to 30 feet']
    ]),
    p('Touch (5 feet) - Ranged Up to 30 feet'),
    h('Lasting'),
    p('Your Jutsu increases its duration from Instant Concentration, up to 1 minute. If you apply this effect an additional time, the duration is increased to Concentration, up to 10 minutes. If you apply this effect, to a jutsu whose current casting time is a Reaction, its duration instead becomes 1 Round. If this effect is added to a jutsu with a Conditional Effect, affected creatures can attempt to remake their saving throws at the end of each of their turns to end this Jutsu\'s effects on them.'),
    h('Speedy'),
    p('Your Jutsu can be cast at a significantly faster speed than most others. The cast time of this Jutsu becomes a Bonus action. If your jutsu deals damage or heals creatures, reduce the damage or healing die by 1. You can take this effect a second time, changing the casting time to a Reaction, if you do reduce your Damage die by 2.'),
    h('Upcast'),
    p('Your Jutsu can be upcast from its current rank, increasing one of its current effects potency per rank upcast. Pick one of the following. If Damage, Shielding or Healing, increase the damage, healing or shielding the jutsu does by 2 damage/healing/shielding die, per rank upcast. (Pick one) If a Conditional Effect, increase the number of ranks of one of the chosen conditions this jutsu applies by +1, per rank upcast.'),
    h('Offensive'),
    h('Bleeding'),
    p('Conditional Effect Your Jutsu has the chance to inflict the Bleeding condition. You can only select this keyword if your Jutsu has the Slashing, Piercing or Wind damage type. Creatures Affected by your Jutsu must make a Dexterity (or Constitution, pick one at jutsu creation) save vs your Ninjutsu Save DC or gain 1 rank of the Bleeding condition Reduce your damage die (if any) by 1, and an additional +1 at C-Rank (2) and S-Rank (3) upon creation. If this effect is added to a Ninjutsu of C-Rank, failing creatures instead gain 2 ranks of Bleeding. This is increased to 3 ranks at B-Rank, 4 ranks at A-Rank and 5 ranks at S-Rank.'),
    h('Burned'),
    p('Conditional Effect Your Jutsu has the chance to inflict the Burned Condition. You can only select this keyword if the Jutsu has Fire Release. Creatures affected by your jutsu must make a constitution save vs your Ninjutsu save DC or suffer the Burned Condition. Reduce your damage die (if any) by 1, and an additional +1 at C-Rank (2) and S-Rank (3) upon creation. If this effect is added to a Ninjutsu of B-Rank, failing creatures instead gain 2 ranks of Burned. This is increased to 3 ranks at S-Rank.'),
    h('Bruising'),
    p('Conditional Effect Your Jutsu has the chance to inflict the Bruised condition. You can only select this keyword if the jutsu has the Earth Affinity. Reduce your damage die (if any) by 1, and an additional +1 at C-Rank (2) and S-Rank (3) upon creation. If this effect is added to a Ninjutsu of B-Rank, failing creatures instead gain 2 ranks of Bruised. This is increased to 3 ranks at S-Rank.'),
    h('Chilled'),
    p('Conditional Effect Your Jutsu has the chance to inflict the Chilled condition. You can only select this Keyword if the Jutsu has Water Release. Creatures affected by your jutsu must make a constitution save vs your Ninjutsu save DC or suffer the Chilled Condition. Reduce your damage die (if any) by 1. Reduce your damage die (if any) by 1, and an additional +1 at C-Rank (2) and S-Rank (3) upon creation. If this effect is added to a Ninjutsu of B-Rank, failing creatures instead gain 2 ranks of Chilled. This is increased to 3 ranks at S-Rank.'),
    h('Corroded'),
    p('Conditional Effect Required Keywords: Medical Your Jutsu has the chance to inflict the Corroded condition. You can only select this Keyword if the Jutsu deals acid damage. Creatures affected by your jutsu must make a constitution save vs your Ninjutsu save DC or suffer the Corroded Condition. Reduce your damage die (if any) by 1, and an additional +1 at C-Rank (2) and S-Rank (3) upon creation. If this effect is added to a Ninjutsu of B-Rank, failing creatures instead gain 2 ranks of Corroded. This is increased to 3 ranks at S-Rank.'),
    h('Critical'),
    p('Increase this jutsu’s critical threat range by +1. You can add this effect an additional time, increasing this jutsu’s critical threat range by an additional +1 for each time you add this effect, after the first.'),
    h('Damage'),
    p('This ninjutsu deals damage. If this jutsu has a Nature Release, it automatically deals the chosen nature releases damage type. If your jutsu has the Medical keyword, it can automatically deal one of the listed Medical damage types (Acid, Necrotic, Poison). If your jutsu has neither Nature Release or Medical, you instead must select another damage type that you qualify for. Select one of the following damage die that your jutsu has based on its rank. Jutsu that deals more types of damage at once splits its damage evenly between each available damage die.'),
    t('Ninjutsu damage die pools by rank', ['Rank', 'Damage die pools'], [
      ['D-Rank', '6d4, 5d6, 4d8, 3d10, 2d12'],
      ['C-Rank', '10d4, 8d6, 6d8, 5d10, 4d12'],
      ['B-Rank', '12d6, 9d8, 7d10, 6d12'],
      ['A-Rank', '15d6, 11d8, 9d10, 7d12'],
      ['S-Rank', '20d6, 15d8, 12d10, 10d12']
    ]),
    h('Empowered Damage'),
    p('Required Effects: Damage Your Jutsu increases its overall damage potential. Increase your damage die by 1. This effect can be taken up to 3 additional times after the first.'),
    h('Envenoming'),
    p('Conditional Effect Your Jutsu has the chance to inflict the Envenomed Condition. You can only select this keyword if the Jutsu has Medical. Creatures affected by your jutsu must make a constitution save vs your Ninjutsu save DC or suffer the Envenomed Condition. Reduce your damage die (if any) by 1, and an additional +1 at C-Rank (2) and S-Rank (3) upon creation. If this effect is added to a Ninjutsu of B-Rank, failing creatures instead gain 2 ranks of Envenomed. This is increased to 3 ranks at S-Rank.'),
    h('Multiple Strikes'),
    p('Required Effects: Damage Your jutsu grants you more than a single Attack Roll. Increase the number of attacks your jutsu makes by +1. Split your damage dice between the attacks evenly. You can take this effect an additional time up to three times total.'),
    h('Powerful Offense'),
    p('Required Effects: Damage Your Jutsu is magnified further. When you would roll your jutsu’s damage, you add your Ninjutsu ability modifier to your first damage roll. You can take this effect an additional time, gaining the ability to add your ability modifier to all damage rolls made with this jutsu.'),
    h('Weakening'),
    p('Conditional Effect Your Jutsu has a chance to inflict the Weakened condition. Creatures affected by your jutsu must make a constitution save vs your Jutsu save DC or suffer the weakened condition. Reduce your damage die (if any) by 1, and an additional +1 at C-Rank (2) and S-Rank (3) upon creation. If this effect is added to a Ninjutsu of B-Rank, failing creatures instead gain 2 ranks of Weakened. This is increased to 3 ranks at S-Rank.'),
    h('Shocking'),
    p('Conditional Effect Your Jutsu has the chance to inflict the Shocked condition. You can only select this keyword if the jutsu has the Lightning Affinity. Reduce your damage die (if any) by 1, and an additional +1 at C-Rank (2) and S-Rank (3) upon creation. If this effect is added to a Ninjutsu of B-Rank, failing creatures instead gain 2 ranks of Shocked. This is increased to 3 ranks at S-Rank.'),
    h('Defensive'),
    h('Empowered Shielding'),
    p('Required Effects: Shielding Your Jutsu increases its overall defensive potential. Increase your shielding die by 1. This effect can be taken up to 3 additional times after the first.'),
    h('Damage Reduction'),
    p('Your jutsu grants you or the target of your jutsu damage reduction vs all sources of damage. Select one of the following dice pools that your jutsu has based on its rank. This pool determines how much damage is reduced from one instance of damage. If the jutsu cast has the Earth Release keyword, increase your chosen damage reduction dice pool by +1 of the listed dice.'),
    t('Ninjutsu damage reduction die pools by rank', ['Rank', 'DR die pools'], [
      ['D-Rank', '2d4, 1d6'],
      ['C-Rank', '3d4, 2d6, 1d8'],
      ['B-Rank', '4d6, 3d8, 2d10'],
      ['A-Rank', '5d6, 4d8, 3d10'],
      ['S-Rank', '6d8, 5d10, 4d12']
    ]),
    h('Powerful Defense'),
    p('Required Keywords: Damage Reduction or Shielding Your Jutsu is magnified further. When you would roll dice for your jutsu’s damage reduction or temporary hit points, you add your Ninjutsu Ability Modifier to the roll.'),
    h('Resistance'),
    p('Your Jutsu grants either yourself or the target creature (your choice during creation) with resistance to a given damage type or Condition. Select between Damage or Condition. Once your choice is made, select one from the following list based on your previous decision. Damage: Bludgeoning, Piercing, Slashing, Earth, Wind, Fire, Cold, Lightning, Acid, Poison, Necrotic, Force Condition: Bleeding, blinded, deafened, bruised, dazed, incapacitated, paralyzed, restrained, slowed, stunned, shocked, burned, chilled, corroded, weakened. This Jutsu\'s target gains resistance to the chosen damage type or condition for this Jutsu\'s duration. This effect can be taken multiple times. Each time you select it, pick a different damage type or condition.'),
    h('Damage Types'),
    p('Requirements Fire Fire Release Cold Water Release Lightning Lightning Release Wind Wind Release Earth Earth Release Bludgeoning - Slashing - Piercing - Poison Medical Acid Medical Necrotic Medical Force - Chakra Fuinjutsu'),
    h('Shielding'),
    p('Required Effects: Lasting Your Jutsu grants temporary hit points to its target. Select one of the following dice pools that your jutsu has based on its rank. This pool determined how much temporary hit points this jutsu grants. If the jutsu cast has the Earth Release keyword, increase your chosen temporary hit point dice pool by +1 of the listed dice.'),
    t('Ninjutsu shielding die pools by rank', ['Rank', 'Shielding die pools'], [
      ['D-Rank', '3d4, 2d6, 1d8'],
      ['C-Rank', '5d4, 4d6, 3d8, 2d10'],
      ['B-Rank', '6d6, 5d8, 4d10, 3d12'],
      ['A-Rank', '7d6, 6d8, 5d10, 4d12'],
      ['S-Rank', '10d6, 8d8, 7d10, 6d12']
    ]),
    h('Control'),
    p('Ninjutsu normally can only have one Conditional Effect or one effect that inflicts a condition. This can be increased to two with Secondary effect or Delayed Effect. Secondary effect and Delayed effect do not stack and cannot be taken together.'),
    h('Blinding'),
    p('Conditional Effect Your jutsu has the chance to inflict the Blinded condition. Creatures affected by your jutsu must make a constitution (or wisdom, pick one at jutsu creation) save vs your Ninjutsu Save DC or suffer the Blinded Condition'),
    h('Deafening'),
    p('Conditional Effect Your jutsu has the chance to cause the deafened condition. Creatures affected by your jutsu must make a constitution (or wisdom, pick one at jutsu creation) save vs your Ninjutsu save DC or suffer the Deafened Condition'),
    h('Knock Back'),
    p('Your Jutsu has the chance to knock a creature back 10ft. Creatures affected by your jutsu must make a Strength saving throw vs your Jutsu Save DC. If this effect is added to a Ninjutsu of C-Rank or higher, failing creatures can instead be pushed back by an additional +10 feet for each rank above D-Rank the jutsu this effect is added to is. If the jutsu cast has the Wind Release keyword, increase the base knock back this effect grants by 5ft, and an additional 5ft for each rank above D-Rank the jutsu is.'),
    h('Poisoning'),
    p('Conditional Effect Required Keywords: Medical Your Jutsu has the chance to inflict the poisoned Condition. Creatures affected by your jutsu must make a constitution save vs your Jutsu save DC or suffer the poisoned condition.'),
    h('Restraining'),
    p('Conditional Effect Your Jutsu has the chance to inflict the restrained condition. Creatures affected by your jutsu must make a Strength (or Dexterity or Constitution) save vs your Jutsu save DC or suffer the restrained condition.'),
    h('Sealing'),
    p('Required Keywords: Fuinjutsu, Chakra Seals (CS), Lasting Your Jutsu seals away a creatures Chakra or Jutsu. Creatures affected by your jutsu must make a Charisma saving throw. On a failed save, the target is marked with a single seal of your description for the duration. This seal does one of the following, of your choice. (Choose during jutsu creation.) Bound Seal. While bound with this seal, the target suffers another Control based Conditional Effect. Decide on this effect. (This does not cost an additional slot.) Restrictive Seal. While bound with this seal, the target cannot cast one Ninjutsu or Genjutsu of your choice. You decide on the jutsu when you cast this jutsu. Fracturing Seal. While bound with this seal, the target increases the cost of jutsu they cast by an amount based on the rank of this jutsu when cast; (D-Rank: +2, C-Rank: +4, B-Rank: +8, A-Rank: +16, S-Rank: +24) This Keyword can be taken up to 3 times. Each time you take this keyword, select an additional effect.'),
    h('Secondary Effect'),
    p('Your jutsu has multiple conditional effects built into it. You can only select this effect if you have another Conditional Effect added to your custom jutsu. Select an additional Conditional Effect adding that effect to your jutsu (This additional Conditional Effect does not cost an additional slot.). You must select one saving throw to use. Your jutsu cannot require more than 1 saving throw. You can select this effect additional times, each time being able to select an additional Conditional Effect.'),
    h('Support'),
    h('Augmentation'),
    p('Prerequisites: Chakra Molding, Self or Touch (Range), Lasting Your Jutsu modifies your targets attacks in some way, making it more lethal, more powerful, accurate or more potent. Select one of the following; Weapon attacks, Ninjutsu Attacks, Taijutsu Attacks or Genjutsu Attacks. This jutsu will only affect the selected type. Next choose which aspect of the chosen attack is being augmented; Attack roll or Damage roll. If Attack roll, for the duration, this jutsu increases the select attack roll by 1d4 for the duration. This bonus is increased to a d6 if added to a B-Rank or higher jutsu. If Damage roll, you must add the Damage effect to this jutsu. (This does not cost an additional slot). When you do select from the following bonus damage dice pools;\n\nYou can select this effect up no more than three times. You cannot select the same combination of attack types and augmentations no matter how many times you may add this effect.'),
    h('Empowered Healing'),
    p('Required Effects: Healing Your Jutsu increases its overall healing potential. Increase your healing die by 1. This effect can be taken up to 3 additional times after the first.'),
    h('Enhancing'),
    p('Required Keywords: Self or Touch, Chakra Molding, Lasting Your Jutsu modifies its targets ability score(s) in some way shape or form. Select one Ability score. While concentrating on this jutsu, the selected Ability score increases by +1. You may take this effect up to 5 times, each time selecting either the same or a different ability score.'),
    h('Powerful Support'),
    p('Required Keywords: Healing Your Jutsu is magnified further. When you would roll dice for your jutsu’s healing. You add your Ninjutsu ability modifier to the roll.'),
    h('Healing'),
    p('Required Keywords: Medical Your Jutsu Heals a creatures hit points. This effect cannot be taken if the jutsu has the Damage effect. Select one of the following die pools that your jutsu heals based on its rank.'),
    t('Ninjutsu healing die pools by rank', ['Rank', 'Healing die pools'], [
      ['D-Rank', '3d6, 2d8, 1d10'],
      ['C-Rank', '5d6, 4d8, 3d10, 2d12'],
      ['B-Rank', '6d6, 5d8, 4d10, 3d12'],
      ['A-Rank', '7d6, 6d8, 5d10, 4d12'],
      ['S-Rank', '10d6, 8d8, 7d10, 6d12']
    ]),
    h('STEP FOUR: FINALIZING THE COST, NAME, AND YOUR LEGACY.'),
    p('The fourth and Final step is to clarify the cost and downtime cost of Your Jutsu, while also coming up with a memorable name. Refer to the chart below to find the Downtime cost and your jutsu’s final cost overall.'),
    t('Final jutsu rank and downtime cost', ['Associated Rank', 'Chakra Cost', 'Downtime Cost (Solo)', 'Downtime Cost (Master)'], [
      ['E-Rank', 'Special (2 Chakra)', '1', '—'],
      ['D-Rank', 'Special (4 Chakra)', '3', '2'],
      ['C-Rank', 'Special (7 Chakra)', '5', '4'],
      ['B-Rank', 'Special (12 Chakra)', '10', '8'],
      ['A-Rank', 'Special (17 Chakra)', '15', '12'],
      ['S-Rank', 'Special (25 Chakra)', '25', '20']
    ])
  ]
};
