import type { DowntimeActivity } from './model';
import { h, p, t } from './block-utils';

export const JUTSU_CUSTOMIZE_ACTIVITY: DowntimeActivity = {
  id: 'jutsu-customize',
  tileLabel: 'Customizing a jutsu',
  modalTitle: 'Customizing a jutsu',
  blocks: [
    h('Jutsu Creation Example (S)'),
    h('Giant Rasengan'),
    h('STEP ONE: DEVELOPING THE CONCEPT'),
    p('Giant Rasengan is a Ninjutsu, which should be apparent from the way the show and manga presents it. We already know from the show what we need it to do. We need it to be a powerful, explosive force when we hit an enemy with it. We know that Naruto came back far stronger than he left. Let’s assume when he returned, we around between levels 9~11. This means that he natively has access to B-Rank jutsu. So, we want to make Giant Rasengan be one step above what he is normally capable of. We want Giant Rasengan to be an A-Rank Jutsu, granting it 5 effect slots.'),
    h('STEP TWO: PREREQUISITES & RESTRICTIONS'),
    p('Going in order Giant Rasengan does not rely on being a Hijutsu, Medical jutsu, Fuinjutsu or require a Nature affinity. Giant Rasengan does need to be powerful, so we want it to rely on Naruto’s class feature, Superiority die. So, we will give it the Required Feature prerequisite, and have it required superiority dice to be cast, granting it a bonus +1 effect slot. We know that while the only Component it requires of Naruto is for him to be able to cast the jutsu in the show, is Chakra Molding the current system requires Naruto to use Hand Seals. So, we have to have it at least require hand signs. We can say that this is part of him casting Shadow clones to help manage the Rasengan like in the show. Finally, we know that its range is Touch since Naruto has to be in Punching Range. Where are we so far? Currently Giant Rasengan looks like this:'),
    h('Giant Rasengan'),
    p('Classification: Ninjutsu Rank: A-Rank Casting Time: - Range: Touch Duration: Instant Components: HS, CM Cost: - Chakra Keywords: Ninjutsu, Required Feature (Superiority die) Description: -'),
    h('STEP THREE: EFFECTS'),
    p('Giant Rasengan is a powerful attack but has support or defensive qualities. It does have a powerful knock back effect, so to decide on the two types Giant Rasengan will pick from, we are left with Offensive and Control. Now, going down the list, we know we have 6 effect slots to fill, so we are going to want the following effects; Clash: The Rasengan’s biggest appeal comes when he clashes with Sasuke’s Chidori. Bruising: We know that this jutsu can cause some physical damage, enough to break bone and leave bruises for sure. Critical: We know that this jutsu can dish out some serious damage if it score a good hit on an adversaries weak point. Damage: Starting off, since this jutsu is A-Rank, we want to go big. We are giving Giant Rasengan a 7d12 Damage die, because its powerful, and we want there to be some noticeable damage when this jutsu lands. We are going to stick with Force damage because this is pure chakra we are dealing with. Empowered Damage: We will Increase the number of damage die with this jutsu once, making it 8d12. Knock Back: The Giant Rasengan has an extremely powerful knockback effect in the show. Since this jutsu is A-Rank, we know that it has a base knockback strength of 10ft, plus 10 feet for every rank above D-Rank, making it have a 40ft knock back distance which is really far. After collecting all of the effects and Chakra Cost of our New Jutsu Here is how it will look.'),
    h('Giant Rasengan'),
    p('Classification: Ninjutsu Rank: A-Rank Casting Time: 1 Action Range: Touch Duration: Instant Components: CM Cost: Special (20 Chakra) Keywords: Ninjutsu, Required Feature (Superiority die), Clash Description: You generate a Powerful sphere of spiraling chakra to strike an enemy with. Make a melee ninjutsu attack. This jutsu have a +1 critical threat range. On a hit, the target creature takes 8d12 force damage and must make a Strength Saving throw, on a failure they are knocked back 40ft.'),
    h('Customizing a jutsu'),
    p('Sometimes you don’t want to create something new from scratch. Sometimes you want to modify something, making it your own. This process is called Jutsu Customization, or Customizing a Jutsu. This process will allow you to take an already defined jutsu that you know and modify its mechanics in multiple ways. You can take the simple Fireball Jutsu and modify it, enhancing it with Lightning Release, so you breathe a ball of multi-elemental destruction, without having to start from scratch. As a Jutsu’s Customizer, you must work with a jutsu that already exists and has predefined limitations built in for you to push to their breaking points. Select one Jutsu that you know. This jutsu is one you begin to modify its core functions, mechanics and potential.'),
    h('Customizing a jutsu rules'),
    h('STEP ONE: MODIFYING YOUR JUTSU’S CORE COMPONENTS'),
    p('The First potential step of customizing/modifying your jutsu is to modify their base component requirements. Changing how this new Jutsu’s version is activated regarding its Components. You can choose to add additional components or remove existing ones at varying chakra cost adjustments. If you do not want to modify this jutsu’s component keywords, then you may skip this step.'),
    h('STEP TWO: MODIFYING YOUR JUTSU’S CORE KEYWORDS'),
    p('The Second potential step of customizing/modifying your jutsu is to modify the base keyword requirements, changing how this new jutsu interacts with the world. Ninjutsu\n\n\n\n• You cannot remove the Ninjutsu or Fuinjutsu Keyword.\n\n\n\n• If your Jutsu does not have a Nature Release Keyword, you can choose to add it so long as you can cast jutsu with that keyword. Adding a Nature release keyword in this way changes the damage type to match the corresponding Nature release.\n\n\n\n• If your jutsu already has a nature release keyword, you cannot remove that keyword.\n\n\n\n• If your jutsu already has a nature release keyword, you may add additional nature release keywords. For each additional nature release keyword, your jutsu’s damage is evenly split between each new damage type.\n\n\n\nTaijutsu\n\n\n\n• If your Jutsu has the Finisher Keyword you cannot remove it.\n\n\n\n• You cannot remove the Taijutsu or Bukijutsu Keyword.\n\n\n\nGenjutsu\n\n\n\n• You cannot remove the Genjutsu or Fuinjutsu Keyword.\n\n\n\n• If you remove a Sensory Keyword (Visual, Auditory, Inhale etc.) you must replace it with another Sensory keyword.'),
    h('STEP THREE: MODIFYING YOUR JUTSU’S RANGE'),
    p('The Third potential step of customizing/modifying your jutsu is to modify its range. Follow the following guide in regards to modifying your jutsu’s range.'),
    h('Self'),
    p('If your Jutsu has a range of self, the next range increment would be Touch. You cannot reduce range below Self'),
    h('Touch'),
    p('If your Jutsu has a range of touch, the next range increment would be 15 feet. If you reduce the Range, the range becomes Self.'),
    h('Ranged'),
    p('If your Jutsu has any range of 10 feet or greater, for each additional range increase, the range of the jutsu increases by double its current range. If you reduce the range, reduce the range by half to a minimum of 5 feet, which is counted as touch.'),
    h('Area Of Effect'),
    p('If your Jutsu has an area of effect, such as a Sphere, Line, Cone, cylinder, cube or any other shape, for each additional range increase, the size of this jutsu increases by 10 feet. If you reduce the area of effect size it decreases by 10 feet.'),
    t('Component keywords', ['Component Keyword', 'Removing Chakra Cost', 'Adding Chakra Cost', 'Downtime Cost'], [
      ['Hand Seals (HS)', '+1', '-1', '1-Week'],
      ['Chakra Seals (CS)', '+1', '-1', '2-Week(s)'],
      ['Weapon (W)', '+1', '-1', '1-Week'],
      ['Ninja Tools (NT)', '+1', '-1', '1-Week']
    ]),
    t('Core keywords', ['Core Keywords', 'Removing Chakra Cost', 'Adding Chakra Cost', 'Downtime Cost'], [
      ['Medical', '-1', '+1', '1-Week'],
      ['Fuinjutsu', '-1', '+1', '1-Week'],
      ['Earth Release', '-', '+2', '3-Week'],
      ['Wind Release', '-', '+2', '3-Week'],
      ['Fire Release', '-', '+2', '3-Week'],
      ['Water Release', '-', '+2', '3-Week'],
      ['Lightning Release', '-', '+2', '3-Week'],
      ['Visual', '-2', '+2', '2-Week'],
      ['Auditory', '-1', '+1', '2-Week'],
      ['Inhale', '-1', '+1', '2-Week'],
      ['Tactile', '-1', '+1', '2-Week'],
      ['Clash', '-1', '+1', '2-Week'],
      ['Finisher', '-1', '+1', '1-Week']
    ]),
    p('If Medical is added, or already a keyword, the user can choose to add either Poison, Acid or Necrotic Damage to the jutsu as if adding a new Nature Release damage type.'),
    t('Jutsu range', ['Component Keyword', 'Decreasing Range Chakra Cost', 'Increasing Range Chakra Cost', 'Downtime Cost'], [
      ['Jutsu Range', '-1', '+1', '1-Week Per Increment']
    ]),
    h('STEP FOUR: MODIFYING DAMAGE & EFFECTS'),
    p('The fourth Step of jutsu modification comes down to altering the strength and power behind your chosen jutsu.\n\n\n\nAll Jutsu, at their core imparts some effect. Effects can include Damage, a new Condition such as poisoned or burned, being stunned, a healing effect, or a defensive effect. While modifying your Jutsu, you manipulate the jutsu’s core formula changing things ever so slightly.'),
    h('Area'),
    p('Chakra Cost: +3 Downtime Cost: 3-Weeks Your Jutsu gains an area of effect in the shape of one of the following: 10ft radius sphere, 15ft Cone, 30ft Cube, 20ft Cylinder or 30ft Line. Creatures must succeed a Dexterity save vs your Ninjutsu Save DC. If your Jutsu requires any other Saving throw to avoid an additional Condition, this Dexterity save replaces that save. This does not count for Effects Selected with "Secondary Effect". You can take this Keyword multiple times, each time increasing the Radius of the jutsu by 15ft. Creatures suffer half damage and no Conditional effects on a successful save.'),
    h('Bleeding'),
    p('Chakra Cost: +2 Conditional Effect Downtime Cost: 2-Weeks Your Jutsu has the chance to inflict the Bleeding condition. You can only select this keyword if your Jutsu has the Slashing, Piercing or Wind damage type. Creatures Affected by your Jutsu must make a constitution save vs your Jutsu Save DC.'),
    h('Burned'),
    p('Chakra Cost: +2 Conditional Effect Downtime Cost: 2-Weeks Your Jutsu has the chance to inflict the burned Condition. You can only select this Keyword if the Jutsu has Fire Release. Creatures affected by your jutsu must make a constitution save vs your Jutsu save DC or suffer the Burned Condition'),
    h('Chilled'),
    p('Chakra Cost: +2 Conditional Effect Downtime Cost: 2-Weeks Your Jutsu has the chance to inflict the chilled Condition. You can only select this Keyword if the Jutsu has the water release keyword. Creatures affected by your jutsu must make a constitution save vs your Jutsu save DC or suffer the chilled Condition.'),
    h('Corroded'),
    p('Chakra Cost: +2 Conditional Effect Downtime Cost: 2-Weeks Your Jutsu has the chance to inflict the corroded Condition. You can only select this Keyword if the Jutsu deals acid damage and has the medical keyword. Creatures affected by your jutsu must make a constitution save vs your Jutsu save DC or suffer the Corroded Condition.'),
    h('Damage/Healing'),
    p('Chakra Cost: +2/-1 Downtime Cost: 2-Weeks If your Jutsu deals damage of any type or heals, you can modify it. By increases the damage dealt or healing received, you can increase or decrease the number of damage dice or healing dice your jutsu has by 1. By increase the number of die, you increase the chakra cost by +2. By reducing the number of die, you reduce the chakra cost by -1.'),
    h('Empowered Damage/Healing'),
    p('Chakra Cost: +3/-2 Downtime Cost: 2-Weeks You can increase or decrease your jutsu’s overall damage or healing potential. Increase or decrease your Damage or healing die by 1 Step. (d4>d6>d8>d10>d12.) By increase the size of the die, you increase the chakra cost by +3. By reducing the size of the die, you reduce the chakra cost by -2.'),
    h('Empowered Shielding'),
    p('Chakra Cost: +2 Downtime Cost: 2-Weeks This Keyword increases this Jutsu’s overall Protective potential. Increase your Temporary hit point Die by 1 Step. (d4>d6>d8>d10>d12.) You can only take this keyword if you already have the Shielding Keyword or provides temporary hit points. This effect can be taken multiple times. Each time you take this effect it increases the Temporary Hit point die up to a maximum of a d12.'),
    h('Enhancing'),
    p('Chakra Cost: +3 Downtime Cost: 3-Weeks Your Jutsu modifies your Ability scores in some way shape or form. At Jutsu modification, select one Ability score. While concentrating on this jutsu, the selected Ability score increases by +1. You may take this keyword up to 5 times.'),
    h('Powerful'),
    p('Chakra Cost: +3 Downtime Cost: 3-Weeks Your Jutsu is magnified further. When you would roll dice for your jutsu’s damage, temporary hit points or any other linked effect based on the required keywords. You add your Jutsu\'s Ability Modifier to the roll.'),
    h('Poisoned'),
    p('Chakra Cost: +2 Conditional Effect Downtime Cost: 2-Weeks Your Jutsu has the chance to inflict the poisoned or envenomed condition. You can only select this Keyword if the Jutsu has Medical. Creatures affected by your jutsu must make a constitution save vs your Jutsu save DC or suffer the Burned Condition.'),
    h('Multiple Strikes'),
    p('Chakra Cost: +2/-2 Downtime Cost: 2-Weeks If your Jutsu grants you more than one Attack Roll. You can Add or subtract 1 attack roll from your jutsu. If you add an additional attack roll to your jutsu increase the chakra cost by +2 and you would roll the same damage as all previous attacks. If you would remove an attack, reduce the chakra cost by -2.'),
    h('Shielding'),
    p('Chakra Cost: +3 Downtime Cost: 3-Weeks Your Jutsu grants Temporary Hit Points. Your Jutsu grants up to 3d4 worth of Temporary hit points. These hit points do not stack with any other ability, feature or jutsu that provides temporary hit points. This keyword can be taken multiple times, increasing the Temp hit points gained by 2d4 up to a maximum of 20d4.'),
    h('Shocking'),
    p('Chakra Cost: +2 Conditional Effect Downtime Cost: 2-Weeks Your Jutsu has the chance to inflict the Shocked condition. You can only select this keyword if the jutsu has the Lightning Affinity. Creatures affected by your jutsu must make a constitution save vs your Jutsu save DC or suffer the Shocked condition.'),
    h('Slowing'),
    p('Chakra Cost: +2 Conditional Effect Downtime Cost: 2-Weeks Your jutsu has the chance to inflict the slowed condition. Creatures affected by your jutsu must make a Strength (or Constitution, Pick one. This cannot be changed later.) save vs your Jutsu save DC or suffer the Slowed condition.'),
    h('Speedy'),
    p('Chakra Cost: +3 Downtime Cost: 3-Weeks Your Jutsu can be cast at a significantly faster speed than most others. Reduce the cast time of your Jutsu from an action to a bonus action. Reduce your Damage die by 1. You can take this Keyword a second time further reducing it to a Reaction, if you do reduce your Damage die by 1 a second time.'),
    h('Stunning'),
    p('Chakra Cost: +7 Conditional Effect Downtime Cost: 3-Weeks Your Jutsu has a chance to inflict the Stunned Condition. Creatures affected by your jutsu must make a constitution save vs your Jutsu save DC or suffer the stunned condition.'),
    h('Unavoidable'),
    p('Chakra Cost: +3 Downtime Cost: 3-Weeks Your Jutsu does not require you to make an attack roll, instead always having the chance to hit your target. Select a target creature within range that you can sense with one of the following senses. (Vision, Hearing, Smell). Target Creature must make a Saving throw vs your Jutsu Save DC. Choose one of the follow saving throws at jutsu creation. Ninjutsu: Strength, Dexterity, Constitution or Wisdom. Genjutsu: Intelligence, Wisdom, Charisma. Taijutsu: Strength, Dexterity or Constitution.'),
    h('Weakening'),
    p('Chakra Cost: +3 Conditional Effect Downtime Cost: 3-Weeks Your Jutsu has a chance to inflict the Weakened condition. Creatures affected by your jutsu must make a constitution save vs your Jutsu save DC or suffer the weakened condition.'),
    h('STEP FIVE: FINALIZING THE COST, NEW NAME & DOWNTIME COST.'),
    p('The Final step is to clarify the final rank, cost and downtime cost of Your Jutsu, while also coming up with a memorable name. When you are finalizing your jutsu there are a few things you need to do in order to also get the final Rank of this new Jutsu. First take your Jutsu\'s damage (If any) and average the amount of potential damage it can deal. This is done by taking the damage die (D4, D6, D8, D10, D12) and using the dies Average. (D4 is 3, D6 is 4, D8 is 5, D10 is 6, D12 is 7). Second you take this average and multiply it by the number of damage die your jutsu has and compare it to the table below to determine the Rank of the Jutsu and the Downtime cost associated with it. If your jutsu does not deal damage, then you instead use the Chakra Cost Column of the table below to determine the Rank of the Jutsu and the Downtime cost associated with it.'),
    t('Final jutsu damage and rank correlation', ['Damage', 'Cost', 'Associated Rank'], [
      ['1-20', '1-9', 'D-Rank'],
      ['21-34', '10-15', 'C-Rank'],
      ['35-49', '15-20', 'B-Rank'],
      ['50-69', '21-28', 'A-Rank'],
      ['70+', '29+', 'S-Rank']
    ])
  ]
};
